apiVersion: v1
kind: Service
metadata:
  name: safeview-api
  labels:
    app.kubernetes.io/name: safeview-api
    app.kubernetes.io/part-of: safeview
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: safeview-api
  ports:
    - name: http
      port: 8000
      targetPort: http
