apiVersion: apps/v1
kind: Deployment
metadata:
  name: safeview-api
  labels:
    app.kubernetes.io/name: safeview-api
    app.kubernetes.io/part-of: safeview
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: safeview-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: safeview-api
        app.kubernetes.io/part-of: safeview
    spec:
      imagePullSecrets:
        - name: safeview-ghcr-pull
      containers:
        - name: api
          image: safeview-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
          envFrom:
            - secretRef:
                name: safeview-aws-credentials
          env:
            - name: AWS_REGION
              value: us-east-1
            - name: AWS_DEFAULT_REGION
              value: us-east-1
            - name: AWS_EC2_METADATA_DISABLED
              value: "true"
            - name: SAFEVIEW_BUCKET
              value: safeview-images-izzet-225989375368-dev
            - name: SAFEVIEW_REGION
              value: us-east-1
            - name: MODERATION_THRESHOLD
              value: "80.0"
            - name: SAFEVIEW_DEBUG
              value: "false"
            - name: SAFEVIEW_LLM_ENABLED
              value: "true"
            - name: SAFEVIEW_LLM_BASE_URL
              value: http://vllm.ai.svc.cluster.local:8000/v1
            - name: SAFEVIEW_LLM_MODEL
              value: mistralai/Mistral-7B-Instruct-v0.3
            - name: SAFEVIEW_LLM_TIMEOUT_SECONDS
              value: "8"
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
