apiVersion: v1
kind: Secret
metadata:
  name: safeview-aws-credentials
  namespace: safeview
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: replace-me
  AWS_SECRET_ACCESS_KEY: replace-me
  AWS_SESSION_TOKEN: ""
